const express = require("express");

const router = express.Router();

const { sendWebHookAPI } = require('./functions/discord.js') 

const facts = ["Cyber-request.net was made by *uddy ;)",
	"Banging your head against a wall burns 150 calories an hour.",
	"In the UK, it is illegal to eat mince pies on Christmas Day!",
	"Pteronophobia is the fear of being tickled by feathers!",
	"When hippos are upset, their sweat turns red.",
	"A flock of crows is known as a murder.",
	"'Facebook Addiction Disorder' is a mental disorder identified by Psychologists.",
	"The average woman uses her height in lipstick every 5 years.",
	"29th May is officially 'Put a Pillow on Your Fridge Day'.",
	"Cherophobia is the fear of fun.",
	"Human saliva has a boiling point three times that of regular water.",
	"If you lift a kangaroo's tail off the ground it can't hop.",
	"Bananas are curved because they grow towards the sun.",
	"Billy goats urinate on their own heads to smell more attractive to females.",
	"The person who invented the Frisbee was cremated and made into frisbees after he died!",
	"During your lifetime, you will produce enough saliva to fill two swimming pools.",
	"If Pinokio says 'My Nose Will Grow Now', it would cause a paradox. Details here.",
	"Polar bears can eat as many as 86 penguins in a single sitting. (If they lived in the same place)",
	"King Henry VIII slept with a gigantic axe beside him.",
	"Movie trailers were originally shown after the movie, which is why they were called 'trailers'.",
	"An eagle can kill a young deer and fly away with it.",
	"Heart attacks are more likely to happen on a Monday.",
	"If you consistently fart for 6 years & 9 months, enough gas is produced to create the energy of an atomic bomb!",
	"in 2015, more people were killed from injuries caused by taking a selfie than by shark attacks.",
	"The top six foods that make your fart are beans, corn, bell peppers, cauliflower, cabbage and milk!",
	"There is a species of spider called the Hobo Spider.",
	"A lion's roar can be heard from 5 miles away!",
	"A toaster uses almost half as much energy as a full-sized oven.",
	"A baby spider is called a spiderling.",
	"You cannot snore and dream at the same time.",
	"The following can be read forward and backwards: Do geese see God?",
	"A baby octopus is about the size of a flea when it is born.",
	"A sheep, a duck and a rooster were the first passengers in a hot air balloon.",
	"In Uganda, 50% of the population is under 15 years of age.",
	"Hitler's mother considered abortion but the doctor persuaded her to keep the baby.",
	"Arab women can initiate a divorce if their husbands don't pour coffee for them.",
	"Recycling one glass jar saves enough energy to watch TV for 3 hours.",
	"Smearing a small amount of dog feces on an insect bite will relieve the itching and swelling.",
	"Catfish are the only animals that naturally have an odd number of whiskers.",
	"Facebook, Skype and Twitter are all banned in China.",
	"95% of people text things they could never say in person.",
	"The Titanic was the first ship to use the SOS signal.",
	"In Poole, ‘Pound World' went out of business because of a store across the road called '99p Stores', which was selling the same products but for just 1 pence cheaper! Read More.",
	"About 8,000 Americans are injured by musical instruments each year.",
	"The French language has seventeen different words for ‘surrender'.",
	"Nearly three percent of the ice in Antarctic glaciers is penguin urine.",
	"Bob Dylan's real name is Robert Zimmerman.",
	"A crocodile can't poke its tongue out :p",
	"Sea otters hold hands when they sleep so they don't drift away from each other.",
	"A small child could swim through the veins of a blue whale.",
	"Elephants are covered with hair.",
	"J.K. Rowling chose the unusual name ‘Hermione' so young girls wouldn't be teased for being nerdy!",
	"Hewlett-Packard's name was decided in a coin toss.",
	"The total number of steps in the Eiffel Tower are 1665.",
	"The Pokémon Hitmonlee and Hitmonchan are based off of Bruce Lee and Jackie Chan.",
	"An arctophile is a person who collects, or is very fond of teddy bears.",
	"Pirates wore earrings because they believed it improved their eyesight.",
	"Los Angeles's full name is 'El Pueblo de Nuestra Senora la Reina de los Angeles de Porciuncula.'",
	"The Twitter bird actually has a name – Larry.",
	"Octopuses have four pairs of arms.",
	"In England, in the 1880's, 'Pants' was considered a dirty word.",
	"It snowed in the Sahara desert for 30 minutes on the 18th February 1979.",
	"Every human spent about half an hour as a single cell.",
	"If you leave everything to the last minute... it will only take a minute.",
	"Unlike many other big cats, snow leopards are not aggressive towards humans. There has never been a verified snow leopard attack on a human being.",
	"The first alarm clock could only ring at 4am.",
	"Birds don't urinate.",
	"Dying is illegal in the Houses of Parliaments – This has been voted as the most ridiculous law by the British citizens.",
	"The most venomous jellyfish in the world is named the Irukandji and is smaller than your fingernail.",
	"The 20th of March is known as Snowman Burning Day!",
	"Slugs have 4 noses.",
	"Panphobia is the fear of everything... which is a pretty unlucky phobia to have.",
	"An apple, potato, and onion all taste the same if you eat them with your nose plugged.",
	"The front paws of a cat are different from the back paws. They have five toes on the front but only four on the back.",
	"A company in Taiwan makes dinnerware out of wheat, so you can eat your plate!",
	"The average person walks the equivalent of twice around the world in a lifetime.",
	"The Bible is the most shoplifted book in the world.",
	"Marco Hort has the world record for fitting 264 straws in his mouth at once!",
	"Mel Blanc – the voice of Bugs Bunny – was allergic to carrots.",
	"California has issued 6 drivers licenses to people named Jesus Christ.",
	"According to Genesis 1:20-22 the chicken came before the egg.",
	"In the Caribbean there are oysters that can climb trees.",
	"Worms eat their own poo.",
	"Squirrels forget where they hide about half of their nuts.",
	"Over 1000 birds a year die from smashing into windows.",
	"The inventor of the Waffle Iron did not like waffles.",
	"George W. Bush was once a cheerleader.",
	"In total, there are 205 bones in the skeleton of a horse.",
	"In 1895 Hampshire police handed out the first ever speeding ticket, fining a man for doing 6mph!",
	"Each year, there are more than 40,000 toilet related injuries in the United States.",
	"Strawberries can also be yellow, green or white. This also affects the taste and some have a similar taste to pineapples.",
	"Mewtwo is a clone of the Pokémon Mew, yet it comes before Mew in the Pokédex.",
	"Every year more than 2500 left-handed people are killed from using right-handed products.",
	"Madonna suffers from garophobia which is the fear of thunder.",
	"China has more English speakers than the United States.",
	"Samuel L. Jackson requested to have a purple light saber in Star Wars in order for him to accept the part as Mace Windu.",
	"Paraskavedekatriaphobia is the fear of Friday the 13th!",
	"Kleenex tissues were originally used as filters in gas masks.",
	"In 1998, Sony accidentally sold 700,000 camcorders that had the technology to see through people's clothes. These cameras had special lenses that use infrared light, which allowed you to see through some types of clothing.",
	"During your lifetime, you will spend around thirty-eight days brushing your teeth.",
	"Ronald McDonald is 'Donald McDonald' in Japan because it makes pronunciation easier for the Japanese. In Singapore he's known as 'Uncle McDonald'.",
	"Donkey Kong got his name because his creator believed ‘donkey' meant ‘stupid' in English and wanted to convey the impression that the character was a 'Stupid Ape'.",
	"The medical name for a butt crack is 'intergluteal cleft'.",
	"People can suffer from a psychological disorder called Boanthropy that makes them believe that they are a cow. They try to live their life as a cow.",
	"The name for the shape of Pringles is called a ‘Hyperbolic Paraboloid'.",
	"There is a McDonalds in every continent except Antartica.",
	"Mr Potato Head was the first toy to be advertised on TV.",
	"A duel between three people is actually called a truel.",
	"The stage before frostbite is called 'frostnip'.",
	"The two tiny holes drilled in every BIC pen is to ensure that the air pressure is the same both inside and outside the pen, which helps the ink flow to the tip.",
	"In South Korea there is an emergency number (113) to report spies.",
	"There are no bridges over the Amazon River.",
	"The process by which bread toasts is called the ‘Maillard Reaction'.",
	"Snails have 14000 teeth and some can even kill you!",
	"Admiral Ackbar from Star Wars Episode VI: Return of the Jedi was not a man in a suit, it was actually a giant puppet.",
	"Sonic the Hedgehog's full name is actually Ogilvie Maurice Hedgehog.",
	"Even though Froot Loops are different colors, they all have exactly the same flavor.",
	"George Clooney did the voice for ‘Sparky' – a gay dog in South Park.",
	"Most toilet paper sold for home use in France is pink.",
	"Marmite was one of most confiscated items at airports from the UK – to overcome this issue, Marmite made smaller ones for travelling.",
	"The human nose can remember 50,000 different scents.",
	"Cards against Humanity bought an island in Maine to preserve wildlife. It is called Hawaii 2.",
	"Daddy longlegs have penises, which technically makes them not a spider.",
	"The television was invented only two years after the invention of sliced bread.",
	"Bullfrogs do not sleep.",
	"The dark region on the north pole of Pluto's moon, Charon, is called Mordor.",
	"Eight of the ten largest statues in the world are of Buddhas.",
	"In 2015, a silver coin with Superman on the heads side was made which is legal tender in Canada. There was only 350,000 produced.",
	"It took the creator of the Rubik's Cube, Erno Rubik, one month to solve the cube after he created it; the current world record is 5.55 seconds.",
	"Japanese square watermelons are ornamental plants and are not edible.",
	"Tigers have striped skin not just striped fur. The stripes are like fingerprints and no two tigers have the same pattern.",
	"Ketchup originated in China as a boiled-down brine of pickled fish and spices called ‘ke-chiap'.",
	"In Morse Code -.- means k.",
	"In 2005, a fortune cookie company called Wonton Food Inc correctly foretold lottery numbers, resulting in 110 winners and an investigation. No fraud was involved.",
	"Two PlayStation 1 games, FIFA 2001 and Gran Turismo 2, has scratch & sniff discs. The FIFA 2001 smelled like a soccer field, while Gran Turismo 2 smelled like car tires.",
	"If you die in Amsterdam with no next of kin, and no friends or family to prepare funeral or mourn over the body, a poet will write a poem for you and recite it at your funeral.",
	"The Himalayan Honey Bee -largest of the honey bees – makes a hallucinogenic honey that tribes collect.",
	"In 2014, Sony made a cassette tape that can store 185TB of data!",
	"The collars on men's dress shirts used to be detachable. This was to save on laundry costs as the collar was the part that needed cleaning the most frequently.",
	"The man who found the 5,000 year old corpse Ötzi the Iceman in 1991 (Oldest natural European mummy) was also found dead frozen in ice in 2004.",
	"In 2014, a missing woman on a vacation in Iceland was found when it was discovered that she was in the search party looking for herself.",
	"If you sneeze while travelling at 60 mph your eyes are closed for an average of 50 feet.",
	"Both Nicholas Cage and Michael Jackson shared the same wife, Elvis Presley's daughter, Lisa Marie Presley.",
	"Alligators will give manatees the right of way if they are swimming near each other.",
	"Crystal – the monkey from The Hangover 2 and Night at the Museum has her own IMDB page!",
	"The 'I'm Feeling Lucky' feature in Google search actually cost Google $110 million a year, as 1% of all searches use this feature and bypass all advertising.",
	"Magpies are considered one of the most intelligent animals in the world, and the only non-mammal species able to recognize itself in a mirror test.",
	"Expedia.com, Hotels.com, Hotwire.com, Trivago, Travelocity, and Orbitz are all owned by the same company, Expedia Inc.",
	"Before the term 'bloopers' was coined, ‘out-takes' were called ‘boners'.",
	"Baked beans are actually not baked, but stewed.",
	"Rowan Atkinson – also known as Mr. Bean – is the voice of Zazu in The Lion King.",
	"The most popular item at Walmart is bananas. They sell more bananas than any other single item they have in stock.",
	"Sunsets on Mars are blue.",
	"‘lbs' comes form the Latin word ‘libra' which means pound.",
	"The small indents in the bottom of frozen pizzas are there to prevent air bubbles forming inside the dough.",
	"The term ‘footage' comes from films being measured in feet, when being edited in the early days of film making.",
	"In 2005, Mark Zuckerberg unsuccessfully tried to sell Facebook for $75 million. Back then it was called TheFacebook.",
	"There is an opposite of albino animals, which aren't white, but black. These are known as Melanistic animals.",
	"Some areas in Scotland and Japan switched to blue street lights at night, and saw a decrease in crime & suicide rates.",
	"The first film with a $100 million budget was True Lies, which was made in 1994.",
	"‘Digging a hole to China' is theoretically possible if you start in Argentina.",
	"There are cells in human body called Faggot cells which cause leukaemia.",
	"Strawberries can also be white or yellow, and some can even taste like pineapples!",
	"Elephants make friends, bury their dead, travel for ‘funerals', speak to each other, and show extreme intelligence.",
	"As of 1998, over 50% of Iceland's population believed in the existence of elves.",
	"The Boston Marathon didn't allow female runners until 1972.",
	"When watermelons are grilled or baked, they lose their granular texture and can even be used as meat substitute, a ‘watermelon steak'.",
	"James Blunt recorded his first album while living with Carrie Fisher. ‘Goodbye My Lover‘ was recorded in her bathroom!",
	"Some cat breeds (called ‘puppy cats') are bred specifically to exhibit dog-like behavior.",
	"In October 2015, United Airlines made a man with Cerebral Palsy crawl off one of its flights. The flight attendants just watched as he struggled.",
	"'Bluetooth' technology was named after a 10th century king, King Harald Bluetooth. He united Denmark and Norway – just like the wireless technology united computers and cell phones.",
	"All dogs are banned from Antarctica since April 1994. This ban was made because of concern that dogs might spread diseases to seals.",
	"Hart Island is the final burial place to over a million of New York City's unclaimed bodies, and thought to be the largest government sponsored mass grave on the earth.",
	"In Slovakia they have Christmas Carp that live in the family bathtub for a few days before they are eaten.",
	"Banks have therapists known as ‘wealth psychologist' who help ultra-rich clients, who are unable to mentally cope with their immense wealth.",
	"In 1999 hackers revealed a security flaw in Hotmail that permitted anybody to log into any Hotmail account using the password ‘eh'. At the time it was called 'the most widespread security incident in the history of the web'.",
	"A small population of Mammoths survived on the Wrangel Island until 1650 BC, about 900 years after the construction of The Great Pyramid of Giza were completed.",
	"The state of Ohio gives out different colored license plates for those convicted of DUI.",
	"The Flintstones was the most profitable network cartoon franchise for 30 years, that's before The Simpsons came along.",
	"The University of Minnesota is older than Minnesota the state itself!",
	"In Japan, you are equally likely to die from being struck by lightning as you are from being shot by a gun.",
	"As of 2016, the site MySpace still gets 50 million visitors a month!",
	"C-3PO and R2-D2 had their own 1985 single season 13 episode spin-off TV series called Star Wars: Droids. The season shown the adventures of R2-D2 & C-3P0 before they joined Luke Skywalker.",
	"People don't sneeze in their sleep due to their brain shutting down the reflex.",
	"If you made $1 every second, it would take you 2,511 years to have more money than Bill Gates (over $79.2 billion dollars).",
	"In 2013 Toy Story was remade shot-for-shot with real toys and real people! Watch the video!",
	"The word 'Jurassic,' which we so often associate with dinosaurs, comes from the Celtic word for 'forest'.",
	"The brain is our fattiest organ, being composed of nearly 60% fat.",
	"Guy Fawkes is the reason guys are called 'guys'.",
	"February used to be the last month of the year, which is why it has the shortest number of days.",
	"Dead people can get goosebumps!",
	"The first film ever shown in the White House was The Birth of a Nation, a pro-white supremacy silent film that the KKK also used as a recruiting tool.",
	"In September 2007, a guy named Kevin Shelley broke 46 wooden toilet seats with his head in one minute to create a world record.",
	"Samuel Jackson has a clause in his film contracts that allows him to play golf during film shoots whenever he wants.",
	"In 1945 the first atomic bomb was created, and was nicknamed 'The Gadget'.",
	"For every child born in Wales since April 2014, the Welsh Government have donated a fruit tree to Ugandan families, to celebrate the birth or adoption of every child.",
	"Restaurants can sing ‘Happy Birthday' now because the copyrights claims are now invalid. Judge George H. King ruled that a copyright filed in 1935, granted only the rights to specific piano arrangements of the music, not the song itself.",
	"Although Australia is home to the largest number of venomous snakes in the world, it averages only one fatal snake bite per year.",
	"Shoe shops used X-Ray machines to measure shoe sizes in the 1940's before the risks of X-Rays were fully understood.",
	"Iguanas have three eyes. Two normal eyes and a third eye on top of their head that only perceives brightness.",
	"Big Ben (Elizabeth Tower) in London is leaning over so much it can now be seen with the naked eye. In 4000 years it will be at the same angle as the tower in Pisa is now.",
	"The reason the taste of artificial banana flavouring and artificial banana flavoured products doesn't taste like bananas is because it is based on a type of banana that was wiped out by a plague in the 1950's.",
	"Australia has over 10,000 beaches. You could visit a new beach everyday for over 27 years!",
	"It was Nicholas Cage who first advised Johnny Depp to pursue a career in acting, during the mid 1980's.",
	"The national animal of Scotland is the Unicorn.",
	"The directors of the film Despicable Me actually wrote their own language for the Minions called Minionise.",
	"The mayor of the Alaskan town, Talkeetna, is called Stubbs and has been mayor of the town since July 1997. Stubbs is a cat.",
	"The Nazis were the first ever people in modern history to start an anti-smoking and tobacco movement.",
	"Due to the humid and moist conditions that a sloth lives in, moss and other similar plants will sometimes grow in its hair. Sloth's also have very bad eyesight. These two factors can sometimes culminate in a sloth grabbing its own arm, whilst thinking it is a branch, and falling to its death!",
	"Every year in June a bizarre festival takes place in the village of Castrillo de Murcia near Burgos in Spain during which men dress up like the devil and then jump over babies born in the previous twelve months of the year! Known as El Colacho, this strange custom is part of the country-wide Corpus Christi celebrations yet only happens in this small village.",
	"Viagra, when dissolved in water, can make cut-flowers stay erect for up to a week longer than they usually would. Try it!",
	"There is an uninhabited island in the Bahamas known as Pig Beach, which is populated entirely by swimming pigs.",
	"Catnip is ten-times more effective at repelling mosquitoes than DEET, the main substance used in insect repellents.",
	"If eaten in one meal, 30 to 90 grams of polar bear liver is enough to kill a human being.",
	"American microbiologist Maurice Ralph Hilleman is accredited with developing 8 of the 14 routine vaccinations used today, these being; Measles, Mumps, Hepatitis A & B, Chickenpox, Meningitis, Pneumonia, and Hemophilia influenza. He also discovered that Chlamydia was not a virus as it was previously thought to be.",
	"In 2002 alone, more people in the U.S. were killed by dogs than in shark attacks in the past 100 years.",
	"American college, Massachusetts Institute of Technology, deems certain students who take courses in Pistol Marksmanship, Archery, Sailing and Fencing as certified ‘Pirates'.",
	"It is predicted that the reason why night insects, such as moths, are attracted to lights is because they mistake them for the light of the moon, which they used to navigate the Earth before mankind made artificial lights.",
	"Justin Bieber once held up a sign from his hotel room window saying 'Go to McDonalds and get me a Big Mac'. He got his Big Mac.",
	"In the early 1900's, Lobster was considered the 'cockroach of the ocean' and was synonymous with the poor – often eaten regularly by the homeless, slaves and prisoners. It wasn't until after World War II that lobster became considered a delicacy and a food associated with the aristocratic classes.",
	"Hares are born with fur and can see whilst rabbits are born ‘naked' and blind.",
	"In the 16th Century, it was a common belief amongst people that the Mandrake Plant grew only where the ejaculated semen of a dead hanged man touched the ground.",
	"Film producer Jeffrey Katzenberg revived The Walt Disney Studios by producing some of their biggest hits: The Little Mermaid, The Lion King, Beauty and the Beast and Aladdin. After these he requested a promotion, and was then abruptly fired by them. He then swore revenge against Disney and founded DreamWorks Studios.",
	"On Black Friday 2014, Cards Against Humanity was removed from being on sale and replaced with a 'Bullsh*t' box, on sale for $6. This box contained 'literal feces, from an actual bull,' as the description stated on their site. This was to protest to the Black Friday shopping craziness where shoppers will literally buy anything on sale. This special Black Friday edition of Cards Against Humanity sold over 30,000 copies, where all buyers actually received a box of bull poo.",
	"Through the use of optogenetics, scientists were able to create a false memory within a mouse's brain. This was done by marking the neurons that fired in the mouse's brain when in one environment, transferring the mouse to a second environment and making these neurons fire whilst shocking the mouse's feet, then transferring the mouse back to the first environment. This made the mouse believe it had had an unpleasant experience in the first environment when in fact it hadn't.",
	"On one of the islands off the West-Coast of Australia lies Lake Hillier. A bright, bubble-gum pink lake! Despite not being the only colored lake in the world, it is unique because it is the only colored lake where scientists have not yet determined what causes it to be such a bright pink.",
	"In 2005, Iraqi insurgents tried to convince American officials that they were holding an American soldier hostage and meant to kill him if Iraqi prisoners were not released. However, their supposed hostage turned out to be a military action figure, not an actual soldier.",
	"In 2014, Netflix spent $0 on marketing its DVD rental business, but over 6 million people still used it.",
	"There is a German technique of swordsmanship known as ‘Mordhau', which consists of gripping the sword inverted with both hands and using brute force to incapacitate your enemy with the pommel or cross-guard!",
	"In 1969, a musician named Jim Sullivan recorded an album called 'U.F.O.', which featured strange lyrics about leaving his family and being abducted by aliens. Sullivan disappeared six years later without a trace, the only piece of evidence being his abandoned car found on a desert road.",
	"In the film Star Wars Episode Three: Revenge of the Sith, every single one of the clone troopers was produced using CGI effects.",
	"There is now technology built into some guns in America that allow a gun's owner to control the safety-catch using their smartphone or tablet.",
	"In China, 2013, scientists were able to grow a human tooth from scratch using stem cells taken from urine.",
	"French author Thomas-Alexander Dumas (The Three Musketeers) is the highest ranking black military official in Europe to date.",
	"Spiked and studded dog-collars derive from the days of the Ancient Greeks, who would give their sheep-dogs sharply spiked collars to protect their necks from wolves whilst they watched over a Sheppard's flock at night.",
	"The world record for the largest pineapple was grown in 2011 by Christine McCallum from Bakewell, Australia. The pineapple measured 32cm long and weighed an incredible 8.28kg!",
	"A study has shown that a male zebra finch is less likely to court a female zebra finch if he did not form any social friendships with female zebra finches when younger.",
	"Artist Salvador Dali would often get out of paying for drinks and meals by drawing on the cheques, making them priceless works of art and therefore un-cashable.",
	"The MMORPG Eve Online hosted the world's largest ever online battle in space on the 28th July 2013. It lasted over five hours and was fought between four-thousand players!",
	"Hawaii‘s state flag is the only US state flag to feature the Union Jack upon it.",
	"Originally, Marge Simpson's hair style was designed that way because the creator, Matt Groening wanted to hide her rabbit ears.",
	"The first computer for business use was developed and pioneered by a British tea shop called Lyons in the 1950's. The LEO (Lyons Electronic Office) contained 6,000 valves and was built by Cambridge mathematician John Simmons to add up the receipts of iced buns!",
	"Surgeons who play video games at least 3 hours a week perform 27% faster and make 37% fewer errors.",
	"The word ‘quarantine' derives from the Venetian dialect of Italian and the words ‘quaranta giorni', meaning ‘forty days'. This is because when it was discovered that ships were infested with plague-carrying rats they were made to sit at anchor outside Venice's city walls for forty days before coming ashore.",
	"There is a blind man in America, Daniel Kish, who uses echolocation to navigate in the same way as a bat! He does this by producing a clicking sound with his tongue and then listening intently for the sound waves to bounce back.",
	"Approximately 1,000,000 dogs in the U.S. are named as the heirs of their owners' wills.",
	"In an interview with Taylor Swift in 2005, she was told, 'If music doesn't work out, you could be a hair model'. Seven years later, the same woman interviewed her again and apologised for what she said.",
	"In a survival situation if you were to drink seawater it would rapidly dehydrate you and soon lead to your death. However, it is vastly less harmful to eat frozen seawater. This is because it contains a tenth the amount of salt as its liquid form, due to the fact that the salt is separated from the water when freezing as it does not fit into the crystalline structure of ice.",
	"In 2012, an Afghan Taliban Commander Mohammed Ashan turned himself in to local authorities, trying to claim the $100 reward prize he had seen on a poster for his arrest.",
	"The organisation 'Cult Awareness Network' once listed Scientology as its ‘#1 Most Dangerous Cult'. Scientology then sued the Cult Awareness Network and bought them out in a hostile takeover.",
	"Due to the extremely warm weather in the summer of 2013, several nuclear power plants across the world, including ones in Japan, Israel and Scotland, were forced to close down because of a sudden increase in the population of Jellyfish. The mass amounts of Jellyfish clogged the filters that draw seawater into the power plants in order to cool down their reactors!",
	"When written down, the word ‘almost' is the longest word in the English language to have all of its letters in alphabetical order.",
	"In Canada, 2012, doctors were able to communicate with a man in a vegetative state. Coma patient Scott Routley was able to tell doctors by using his thoughts that he was not in any pain.",
	"The country of Lichtenstein has an extremely low crime rate, and according to one member of their police there hasn't been a murder in Lichtenstein since the late 1990's! Lichtenstein's entire Police Force consists of 91 officers and 34 civilian staff just – 125 in total.",
	"A study was conducted that showed customers in a book-store were 3.48 times more likely to peruse romantic books if the store smelt of chocolate, and 5.93 times more likely to buy them!",
	"Sonic the Hedgehog has registered itself in Guinness Book of World Records for being the fastest gaming character ever.",
	"France has conducted 210 nuclear weapon tests, more than the United Kingdom, China, India, and North Korea combined! This is scarcely a fifth of the amount conducted by the United States, however, who have conducted roughly 1,054 tests.",
	"Iran carries out more gender-change operations than any other country in the world. According to official statistics Iran has somewhere between 15,000 and 20,000 transsexuals inhabiting it, although unofficial statistics place that number at approximately 150,000!",
	"There is an Australian man, James Harrison, who has a singularly unique blood plasma composition that has been used to cure Rhesus disease, a hemolytic disease that affects newborn babies. He has donated his blood plasma over 1000 times.",
	"In 2011, Chinese surgeons were able to remove the rusty, 4 inch end of a broken blade from the skull of a man who claimed it had been stuck in there for four years! The man had been stabbed in the lower-jaw by a thief four years previously and the blade had snapped off, getting stuck in his head.",
	"Put A Pillow on Your Fridge Day, is celebrated on 29th May in Europe & USA and supposedly brings good luck and wealth to the household.",
	"When people are struck by lightening the mark that appears on their afflicted area afterwards looks like an intricately detailed silhouette of a fern tree and is known as ‘lightening tree' or sometimes ‘lightening flower'. This occurs due to delicate capillaries rupturing beneath the skin from the shock of the electrical discharge.",
	"In Bordeaux, France, 1940, Portuguese diplomat Aristides de Sousa Mendes issued an estimated 30,000 Portuguese travel visas in order to Jewish families flee persecution from the Nazis. Once his superiors had learned of his actions, he was ordered back to Portugal, dismissed from office and denied his pension benefits. Sousa Mendes went on to die in 1954, impoverished and unsung.",
	"Household-cleaner Cillit Bang was used to clean plutonium stains away in a defunct nuclear power-plant in Scotland as it was being dismantled. Bang and the radiation is gone!",
	"On 23rd May 2012, the American nuclear submarine USS Miami was damaged beyond repair by a fire whilst it was docked up in a Naval Shipyard. Although the start of this fire was unclear at first, civilian employee Casey J. Fury later admitted to starting the fire in order to 'get out of work early'. For this he was sentenced to 17 years in a federal prison ordered to pay $400 million in recompense.",
	"The tea-bag was an accidental invention. This occurred in 1908 when tea merchant Thomas Sullivan distributed his tea samples in small, silken bags. His customers, not understanding that these were samples, dunked them and suddenly Sullivan was swamped with orders for his ‘tea bags'!",
	"As of May 2015, 2.3 Million Americans still subscribed to AOL Dial Up Internet.",
	"Nokia was originally founded in 1865 as a paper printing company. Apt, to say when it was founded paper was one of the world's most used methods of long-distance communication!",
	"The world's biggest ever recorded turtle was a Leatherback Turtle that washed up Harlech Beach, Wales, in 1988. It was estimated to be 100 years old, and was almost 9 foot in length weighing a tumultuous 2,016 lbs!",
	"Archeologists in London have found a Mesolithic tool-making factory that gives substantial proof human beings were living on the River Thames 7,000 B.C. That's over 9,000 years ago!",
	"A Dachshund (a.k.a. a sausage dog) was originally bred to hunt in low, narrow badger burrows. In fact, the term ‘Dachshund' translates from German as ‘badger dog'!",
	"In early 2013, guards inside a prison camp in the Komi region of Russia caught a cat climbing over the fence that was being used to smuggle mobile phones, chargers and batteries into the prison. This was done by people taping the equipment to the cat's back and then having the cat climb over the fences to reach the prisoners inside!",
	"The word ‘oxymoron' is itself an oxymoron. This is because it derives from Ancient Greek where ‘oxy' means ‘sharp' and ‘moros' means ‘stupid'.",
	"Bruno Mars' birth name is Peter Gene Bayot Hernandez. His stage name, 'Bruno Mars', was inspired by the wrestler Bruno Samartino. This was because as a child, Bruno was independent, confident and strong-willed, like the wrestler. ‘Mars‘ came along because he was often told he was 'out of this world' by the girls, so he used the planet Mars as his last name.",
	"2013 was the first year since 1987 to feature four different numbers.",
	"The term ‘deadline' comes from the American Civil War. Prisoners would have lines drawn around them in the dirt, and if they crossed this line then they would be executed by their guards. Both prisoners and guards soon took to calling this line the ‘dead line'.",
	"There is an island that sits in the middle of the Bay of Bengal called North Sentinel Island. The indigenous people of this island have never been colonized by the outside world and are extremely hostile, attacking anyone who invades their land without fear. What makes this even more interesting is that, when taken from the island, these people exhibit symptoms of a mystery illness before dying if they are not returned.",
	"In Soviet labor camps, prisoners would ingest a condom attached to a length of rubber tubing, fill it up with raw alcohol then smuggle themselves back into the camp. Once there they would be suspended upside down by the other prisoners and used as a human keg.",
	"During the First World War, so many starving wolves had amassed together in a great pack that opposing German and Russian forces formed a temporary alliance in order to fight them off!",
	"Take Your Houseplants for a Walk Day is celebrated on 27th July, on this bizarre day, people walk their houseplants around, so they can get to know their environment a little more, which supposedly provides the plants with a sense of knowing and familiarization to their surround areas.",
	"In 2010 Japan's government decided to check up on many of the more-aged members of its community. What it found, however, was that many of Japan's older citizens had died, and that their children had hid their deaths in order to carry on cashing their numerous pension checks!",
	"Murphy beds have been attributed as the cause of people's deaths before. Most recently in 2005 when two women were trapped and suffocated to the death by their Murphy bed.",
	"The least financially successful Harry Potter film made approximately $90 million more than the most successful Twilight movie.",
	"In late 2013, the first carnivorous mammal to be discovered within the Western hemisphere was found by Dr. Kristofer Helgen. It is called the Olinguito and is a member of the Raccoon-family.",
	"In 2002, Brazilian mechanic Alfredo Moser invented a new type of lamp that uses absolutely no electric whatsoever! The Moser-lamp is created using a plastic bottle filled with water and the smallest bit of bleach (to stop the bottle turning green with algae), and works through the refraction of natural light – kicking out roughly 40 – 60 watts per lamp! They are becoming popular in many countries where electricity is an expensive commodity, and have been fitted in over 140,000 homes in the Philippines. Despite the success of his invention, Alfredo Moser has not become rich from it, but has instead a great sense of pride at his altruism.",
	"In August 2013, Michigan man Darryl See was released from intensive care after being hit head-on by a high speed Amtrak train. Darryl See, who was listening to music and didn't hear the train's repeated horn-blows, was reportedly thrown 20 feet from the track by the train that was traveling at 110mph!",
	"New research provided suggests that NASA craft, Voyager 1, has left our solar system – making it the first man-made object to leave the solar system! Launched in 1977, the Voyager 1 probe is not set to run out of propellant energy until 2025, meaning by then it could have delved even deeper into interstellar space.",
	"In mid 2013, an earthquake-proof church was constructed in Christchurch, New Zealand, using mainly cardboard as the primary building material! Constructed from 98 giant cardboard tubes coated in multiple layers of waterproof polyurethane the ‘cardboard cathedral' cost $6 million to build and is designed to last for up to 50 years!",
	"In 1995, strange 7-foot circular patterns were discovered on the ocean's floor. Deemed the ‘crop circles of the sea', these mysterious patterns went unanswered for until early 2011 when it was discovered that 5-inch long male puffer-fish were the culprits. After studying these animals, scientists have discovered that the meticulous creation and upkeep of these patterns by the puffer-fish serve as an attraction for the opposite sex as well as a nest for the female puffer-fish's eggs.",
	"In the bioengineering department of the University of Illinois, researchers have created small ‘biobots', partly out of synthetic gel and partly out of muscle cell, that can move on their own. Whilst only a small scientific step, this is the building blocks for ‘nanotechnology': tiny devices that could exist within the human body, freely detecting illness and administering medication.",
	"In the Vietnam-War, American soldiers believed the playing card The Ace of Spades to be a symbol of superstition and fear amongst the Viet Cong soldiers. So much so that Charlie Company of the army's 2nd battalion ordered crates of this single card in bulk so they could scatter it in Viet Cong terrain and litter the bodies of dead Viet Cong soldiers with it. The Ace of Spades was not feared by the Viet Cong.",
	"The bumblebee bat is not only the world's smallest bat, but it is also the world's smallest mammal. These cute little creatures weigh only 2 grammes. They are 29 to 33mm in length, with a wingspan of approximately 170mm!",
	"In 2007, a 1000-gallon inflatable swimming pool was stolen from someone's back-garden without a single drop of water being found!",
	"You are three times more likely to get a virus on your computer from a Religious website than from a Porn website.",
	"The wild boar was once thought to be extinct within Ireland, but over 50 of them have been found and caught roaming the country in 2013 alone! They are thought to have been re-introduced to the country illegally by poachers.",
	"Colombian drug-lord Pablo Escobar kept four Hippos in his estate before his death in 1993. Deemed too much hassle to move by authorities, his Hippos were left there and have since bred and escaped becoming an invasive species of Colombia.",
	"It is estimated that in the Amazon Rainforest alone there between 20-40 million different species of animals, most of which are insects, as well as over 40,000 species of plant!",
	"There is a hybrid-sport birthed from the comic book of a French artist and filmmaker called Chess Boxing. This consists of six four-minute chess rounds interposed with five three-minute boxing rounds. A contestant wins when they get a knock-out or technical stoppage within the boxing round, or through a check-mate or forfeit within the chess rounds.",
	"On the 20th August 2013 the world record for the world's biggest Lego-tower was smashed by a group of students from Delaware, USA. Their tower measured 112 feet in height and was constructed using more than 500,000 pieces of Lego!",
	"An Egyptian necklace dated as being 5,000 years old has been found to have been made out of meteoritic metals. The nine beads were found to contain high levels of nickel, cobalt, prosperous and germanium – all characteristic metals of a meteorite. Even more interesting is how the beads were made. They were rolled from thin sheets of metal which contradicts what historians believed about the smithing abilities of ancient Egyptians, having previously believed the beads to have holes drilled through them.",
	"American photographer Harry Whittier Frees dressed his cats – as well as the cats and dogs of his neighbors – in small, people-like clothing and gave them props before photographing them. The black-and-white pictures of these cats and dogs were often given witty captions by Frees, making them the (unknowingly) first LOLcat memes!",
	"Gorillas can catch human colds and other illnesses.",
	"A newborn Chinese water deer is so small it can almost be held in the palm of the hand.",
	"Ostriches can run faster than horses, and the males can roar like lions.",
	"A lion in the wild usually makes no more than twenty kills a year.",
	"The female lion does ninety percent of the hunting.",
	"The world's smallest dog was a Yorkshire Terrier, which weighed just four ounces.",
	"Turtles, water snakes, crocodiles, alligators, dolphins, whales, and other water going creatures will drown if kept underwater too long.",
	"Almost half the pigs in the world are kept by farmers in China.",
	"On average, dogs have better eyesight than humans, although not as colorful.",
	"Deer have no gall bladders.",
	"There is an average of 50,000 spiders per acre in green areas.",
	"Snakes are carnivores, which means they only eat animals, often small ones such as insects, birds, frogs and other small mammals.",
	"In Alaska it is illegal to whisper in someone's ear while they're moose hunting.",
	"The bat is the only mammal that can fly.",
	"The leg bones of a bat are so thin that no bat can walk.",
	"Some male songbirds sing more than 2000 times each day.",
	"The only mammals to undergo menopause are elephants, humpback whales and human females.",
	"Blue-eyed lemurs are one of two (non-human) primates to have truly blue eyes.",
	"A tarantula spider can survive for more than two years without food.",
	"For every human in the world there are one million ants.",
	"If you lift a kangaroo's tail off the ground it can't hop – they use their tails for balance.",
	"If you keep a goldfish. in a dark room, it will become pale!",
	"Cows can sleep standing up, but they can only dream lying down.",
	"The sentence 'The quick brown fox jumps over a lazy dog.' uses every letter of the alphabet.",
	"The average fox weighs 14 pounds.",
	"The scientific name of the red fox is Vulpes vulpes.",
	"Alligators can live up to 100 years.",
	"A single elephant tooth can weigh as much as 9 pounds.",
	"The turkey is one of the most famous birds in North America.",
	"A housefly hums in the key of F.",
	"During World War II, Americans tried to train bats to drop bombs.",
	"Canis lupus lupus is the scientific name for a grey wolf.",
	"To escape the grip of a crocodile's jaw, push your thumb into its eyeballs-it will let you go instantly.",
	"It is much easier for dogs to learn spoken commands if they are given in conjunction with hand signals or gestures.",
	"Even a small amount of alcohol placed on a scorpion will make it go crazy and sting itself to death!",
	"Male rabbits are called 'bucks,' females are 'does.'",
	"The flamingo can only eat when its head is upside down.",
	"Animals generate 30 times more waste than humans which is 1.4 billion tons every year.",
	"Ants never sleep. Also they don't have lungs.",
	"A group of owls is called a parliament.",
	"Just one cow gives off enough harmful methane gas in a single day to fill around 400 litre bottles.",
	"Apple and pear seeds contain arsenic, which may be deadly to dogs.",
	"Cows have one large stomach that is divided into four compartments to go through the different stages of digestion.",
	"An anteater is nearly 6 feet long, yet its mouth is only an inch wide.",
	"The blue whale weighs as much as thirty elephants and is as long as three Greyhound buses.",
	"A herd of sixty cows is capable of producing a ton of milk in less than a day.",
	"A grasshopper can leap 20 times the length of its own body.",
	"At birth, baby kangaroos are only about an inch long – no bigger than a large water bug or a queen bee.",
	"The smell of a skunk can be detected by a human a mile away.",
	"There is a butterfly in Africa with enough poison in its body to kill six cats!",
	"Cats have lived with people for only 7,000 years.",
	"A black panther is really a black leopard.",
	"The honey bee has been around for 30 million years.",
	"The dumbest dog in the world is the Afghan hounds.",
	"A cat has 32 muscles in each ear.",
	"A dog's shoulder blades are unattached to the rest of the skeleton to allow greater flexibility for running.",
	"Tigers have striped skin as well as their fur.",
	"Hippos can run faster than humans!",
	"The Latin name for moose is alces alces.",
	"The earliest European images of dogs are found in cave paintings dating back 12,000 years ago in Spain.",
	"Baby horses can walk and run after just a few hours of being born.",
	"The kangaroo's ancestors lived in trees. Today there are eight different kinds of tree kangaroos.",
	"A woodpecker can peck 20 times per second.",
	"The great horned owl has no sense of smell.",
	"Scientists have performed brain surgery on cockroaches.",
	"The flea can jump up to 200 times its own height. This is equal to a man jumping the Empire State Building in New York."]

router.get('/', (req, res) => {
  res.send({data:facts[Math.floor(Math.random()*facts.length)]})
  sendWebHookAPI("fact")
})

module.exports = router;