const express = require("express");

const router = express.Router();

const { sendWebHookAPI } = require('./functions/discord.js') 

const insults = ["go fuck yourself",
	"stfu faggot",
	"nobody cares about you",
	"kill yourself",
	"nobody would notice if you just ended it right here right now",
	"your mom is disappoited in you",
	"you're a failure to your family",
	"your mom looks like the michelin man",
	"your nan looks like the marshmello man from ghostbusters",
	"You shameful gluttons and servants of your bellies are better suited to be swineherds and keepers of dogs",
	"wubba lubba dub dub I just fucked ya mom in the tub",
	"lick lick lick my balls",
	"Your words are so foolishly and ignorantly composed that I cannot believe you understand them.",
	"You are worthy only to be mocked by the words of error.",
	"It's better to let someone think you are an Idiot than to open your mouth and prove it.",
	"You have two parts of brain, 'left' and 'right'. In the left side, there's nothing right. In the right side, there's nothing left.",
	"Is your ass jealous of the amount of shit that just came out of your mouth?",
	"If I wanted to kill myself I'd climb your ego and jump to your IQ.",
	"Two wrongs don't make a right, take your parents as an example.",
	"You are so ugly if they laid you on the beach, not even the tide would take you.",
	"Talking to a liberal is like trying to explain social media to a 70 years old.",
	"I'm not insulting you. I'm describing you.",
	"Your birth certificate is an apology letter from the condom factory.",
	"upport bacteria - they're the only culture some people have.",
	"You're so ugly, when your mom dropped you off at school she got a fine for littering.",
	"You must have been born on a highway because that's where most accidents happen.",
	"I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
	"The only way you'll ever get laid is if you crawl up a chicken's ass and wait.",
	"It looks like your face caught on fire and someone tried to put it out with a hammer.",
	"If laughter is the best medicine, your face must be curing the world.",
	"You sound reasonable. It must be time to up my medication!",
	"I'm jealous of all the people that haven't met you",
	"There's only one problem with your face, I can see it",
	"Hey, you have something on your chin... no, the 3rd one down.",
	"You are proof that evolution CAN go in reverse.",
	"What language are you speaking? Cause it sounds like bullshit.",
	"Don't you love nature, despite what it did to you?",
	"If I had a face like yours, I'd sue my parents.",
	"If what you don't know can't hurt you, you're invulnerable.",
	"Stupidity is not a crime so you are free to go.",
	"I'm glad to see you're not letting your education get in the way of your ignorance.",
	"If you really want to know about mistakes, you should ask your parents.",
	"You're the reason the gene pool needs a lifeguard.",
	"Roses are red, Violets are blue. I've got five fingers, The middle one is for you.",
	"As an outsider, what do you think of the human race?",
	"I would ask you how old you are but I know you can't count that high.",
	"If your going to be two faced at least make one of them pretty.",
	"We all sprang from apes, but you didn't spring far enough.",
	"You're so fake, Barbie is jealous.",
	"You look like a before picture.",
	"You are living proof that manure can sprout legs and walk.",
	"I'd like to see things from your point of view, but I can't seem to get my head that far up your ass.",
	"You sound a lot like the Terms and Conditions, that's why I don't give a shit about what you have to say.",
	"If shit was music, you'd be an orchestra.",
	"Karma takes too long, I'd rather beat the shit out of you just now.",
	"You do realize makeup isn't going to fix your stupidity?",
	"Aww, it's so cute when you try to talk about things you don't understand.",
	"I may love to shop but I'm not buying your bullshit.",
	"Calling you an idiot would be an insult to all stupid people.",
	"If I wanted to hear from an asshole, I'd fart.",
	"Oh, what? Sorry. I was trying to imagine you with a personality.",
	"You're so ugly, you scared the crap out of the toilet.",
	"Ordinarily people live and learn. You just live.",
	"I would love to insult you... but that would be beyond the level of your intelligence.",
	"Whats the difference between your girlfriend and a walrus? One has a moustache and smells of fish and the other is a walrus.",
	"Your gene pool could use a little chlorine.",
	"You're about as useless as an asshole with tastebuds.",
	"How many times do I have to flush before you go away?",
	"Which sexual position produces the ugliest children? Ask your mother.",
	"I had prepared for a battle of wits but I see you came unarmed.",
	"You're so sad that even Bob the Builder can't fix your life.",
	"What would you call a woman who goes out with You? Desperate.",
	"you'll never be the man your mother is.",
	"Do you wanna lose ten pounds of ugly fat? Cut off your head.",
	"Keep talking, someday you'll say something intelligent.",
	"Whatever kind of look you were going for, you missed.",
	"You're proof that god has a sense of humor.",
	"What is the difference between a joke and 3 dicks? Your mom can't take a joke.",
	"Your cock is so small you could use it to floss teeth.",
	"Sorry I didn't respond to you just now. I was doing something productive and not wasting my precious time with your lowlife speeches.",
	"You stare at frozen juice cans because they say ,concentrate.",
	"You look like a person that would exchange one of your chromosomes for a Big Mac.",
	"When I look into your eyes, I see straight through to the back of your head.",
	"For those who never forget a face, you are an exception.",
	"Where did you buy your stupidity? Or it was given for free and you took an overdose?",
	"Please, keep talking. I always yawn when I am interested.",
	"Did your parents keep the placenta and throw away the baby?",
	"Are your parents siblings?",
	"I'm not being rude, you're just insignificant.",
	"Look to your left --------------> I said left you idiot!",
	"Your blow up date saw you naked, and self deflated.",
	"I can't believe that you were the sperm that won the race, and your still slow.",
	"You're street smart. Sesame Street smart.",
	"Some people are so happy to see you in the parade, so they have another reason to crap on it.",
	"If you were on fire and I had water I would drink it.",
	"You're about as useful as a bucket without a bottom.",
	"What costume are you wearing for Halloween? Oh yeah, I forgot u don't need one ur ugly as hell.",
	"You have enough fat to make another human.",
	"You have more chins than Chinatown.",
	"Every time you open your mouth, some idiot starts talking."]

router.get('/', (req, res) => {
  res.send({data:insults[Math.floor(Math.random()*insults.length)]})
  sendWebHookAPI("insult")
})

module.exports = router;